include $(TOPDIR)/rules.mk
include $(INCLUDE_DIR)/kernel.mk

PKG_NAME:=rtl8822bu
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

# The exact flags needed to find basic_types.h
PKG_EXTRA_CFLAGS += -I$(PKG_BUILD_DIR)/include
PKG_EXTRA_CFLAGS += -I$(PKG_BUILD_DIR)/hal/phydm
PKG_EXTRA_CFLAGS += -I$(PKG_BUILD_DIR)/hal/halmac
PKG_EXTRA_CFLAGS += -I$(PKG_BUILD_DIR)/core/crypto
PKG_EXTRA_CFLAGS += -DCONFIG_RTW_SW_CRYPTO

define KernelPackage/rtl8822bu
  SUBMENU:=Wireless Drivers
  TITLE:=Realtek 8822BU USB WiFi
  DEPENDS:=+kmod-usb-core +kmod-cfg80211
  FILES:=$(PKG_BUILD_DIR)/rtl8822bu.ko
  AUTOLOAD:=$(call AutoProbe,rtl8822bu)
endef

define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)
	cp -r ./* $(PKG_BUILD_DIR)/
endef

# The original core objects you had
rtl8822bu-objs := \
	core/rtw_cmd.o core/rtw_security.o core/rtw_debug.o core/rtw_mlme.o \
	core/rtw_pwrctrl.o core/rtw_io.o core/rtw_eeprom.o core/rtw_wlan_util.o \
	core/rtw_xmit.o core/rtw_recv.o core/rtw_sta_mgt.o core/rtw_ap.o \
	core/rtw_mlme_ext.o core/rtw_ieee80211.o core/rtw_vht.o core/rtw_mi.o \
	core/rtw_btcoex.o core/rtw_sreset.o core/rtw_beamforming.o core/rtw_chplan.o \
	core/rtw_rf.o core/rtw_odm.o core/rtw_swcrypto.o \
	os_dep/osdep_service.o os_dep/linux/os_intfs.o os_dep/linux/usb_intf.o \
	os_dep/linux/usb_ops_linux.o os_dep/linux/ioctl_linux.o os_dep/linux/xmit_linux.o \
	os_dep/linux/mlme_linux.o os_dep/linux/recv_linux.o os_dep/linux/ioctl_cfg80211.o \
	os_dep/linux/rtw_cfgvendor.o os_dep/linux/wifi_regd.o \
	hal/hal_intf.o hal/hal_com.o hal/hal_com_phycfg.o hal/hal_phy.o \
	hal/hal_dm.o hal/hal_dm_acs.o hal/hal_btcoex_wifionly.o hal/hal_btcoex.o \
	hal/hal_hci/hal_usb.o hal/hal_halmac.o hal/HalPwrSeqCmd.o \
	hal/led/hal_led.o hal/led/hal_usb_led.o \
	hal/rtl8822b/rtl8822b_halinit.o hal/rtl8822b/rtl8822b_mac.o \
	hal/rtl8822b/rtl8822b_cmd.o hal/rtl8822b/rtl8822b_phy.o \
	hal/rtl8822b/rtl8822b_ops.o hal/rtl8822b/hal8822b_fw.o \
	hal/rtl8822b/usb/rtl8822bu_halinit.o hal/rtl8822b/usb/rtl8822bu_halmac.o \
	hal/rtl8822b/usb/rtl8822bu_io.o hal/rtl8822b/usb/rtl8822bu_xmit.o \
	hal/rtl8822b/usb/rtl8822bu_recv.o hal/rtl8822b/usb/rtl8822bu_ops.o \
	hal/efuse/rtl8822b/HalEfuseMask8822B_USB.o

# The extra objects we need to finish linking
rtl8822bu-objs += core/crypto/aes-internal.o core/crypto/aes-internal-enc.o \
                  core/crypto/sha256-internal.o core/crypto/sha256.o core/crypto/ccmp.o

obj-m += rtl8822bu.o

define Build/Compile
	$(MAKE) -C $(LINUX_DIR) \
		$(KERNEL_MAKE_FLAGS) \
		M="$(PKG_BUILD_DIR)" \
		EXTRA_CFLAGS="$(PKG_EXTRA_CFLAGS)" \
		modules
endef

$(eval $(call KernelPackage,rtl8822bu))